version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17

  pre_build:
    commands:
      - cd resource/section-3/my-angular-project
      - npm ci

  build:
    commands:
      - pwd
      - ls -la
      - ls -la resource || true
      - ls -la resource/section-3 || true
      - find resource -maxdepth 4 -type d -name "my-angular-project" -print || true
      - cd resource/section-3/my-angular-project
      - test -f angular.json && echo "FOUND angular.json" || echo "NO angular.json"
      - ng version
      - ng build -c production

artifacts:
  base-directory: resource/section-3/my-angular-project/dist
  files:
    - '**/*'
