version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd resource/section-3/my-angular-project
      - npm ci
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build -c production
artifacts:
  base-directory: resource/section-3/my-angular-project
  files:
    - '**/*'
